[build]
functions = "dist"
publish = "dist"
# This command builds the site
command = "yarn build"

[[redirects]]
from = "/"
to = "/.netlify/functions/spaceapi-gateway"
status = 200

[[plugins]]
package = 'netlify-plugin-contextual-env'

[plugins.inputs]
mode = 'prefix'
